# Setup
title:        YAKANG GAO'S BLOG
tagline:      Talk is cheap, show me the code.
baseurl:      "http://rever4433.github.io"
paginate:     1

# About/contact
author:
  name:       YAKANG GAO
  url:        http://gaoyakang.tk

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown