# Site settings
title: YAKANG's Blog
header-img: img/home-bg.jpg
email: gao2524289@outlook.com
copyright_name: YAKANG GAO
description: "Talk is cheap , show me the code."
baseurl: ""
url: "https://rever4433.github.io/"
twitter_username: rever4433
github_username:  rever4433
facebook_username: rever4433
email_username:  gao2524289@outlook.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
# Friends
friends: [
    {
        title: "Foo Blog",
        href: "http://foo.github.io/"
    },
    {
        title: "Bar Blog",
        href: "http://bar.github.io"
    }
]